### ISSUE TITLE
Проблема с yarn

### ISSUE THREAD

**Issue by KentCpu** [atls/reactjs#126]
### Скоуп

Установка зависимостей проекта

### Описание

Команда `yarn install` не устанавливает зависимости при версии 0.0.1-git.20220304.hash-6afc8ff, но после изменения версии Yarn на 3.1.1 зависимости устанавливаются без проблем.

### Контекст

Похожая проблема уже встречалась на проекте #85.

### Воспроизведение

Ubuntu@22.04
1. В корневом каталоге проекта выполнить `yarn install`
2. Команда завершилась успешно, но зависимости не были установлены

Windows 10
1. В корневом каталоге проекта выполнить `yarn install`
2. Команда завершилась успешно, но зависимости не были установлены.

### Ожидаемое поведение

Успешная установка зависимостей.

### Действия

Ubuntu@22.04
1. `yarn set version 3.1.1`
2. `yarn install`
3. Зависимости установлены

Windows 10
1. `yarn set version 3.1.1`
2. `yarn install`
3. Зависимости установлены

### Вопрос

1. Возможно я делаю что-то не так ?
2. @Nelfimov, у вас была похожая проблема, можете подсказать, как вы справились ?
3. Как при версии yarn@3.1.1 запустить `yarn check` ?

**Comment by Nelfimov** [comment]
Закоммитил потенциальный фикс. По истории проблемы она была на Ubuntu, а у меня мак, поэтому "потенциальный".

Что сделал:

- Обновил версию `yarn` до последней 20230627
- Зафиксировал в `resolutions` последнюю рабочую версию `typescript` 4.6.2
- В .yarnrc добавил `enableGlobalCache: false`

А теперь подробности:

- В наших проектах используется кастомная версия `yarn` с `Webpack`, которую @TorinAsakura допилил. Только на ней работают наши проекты и именно поэтому мы держим ее отдельным файлом в каждом проекте. Поэтому когда ты пытаешься запустить `yarn check` на официальной сборке, `yarn` не понимает такой команды потому что она есть только в нашей кастомной.

- `yarn check` это общая команда, которую выполняем до коммитов. Она запускает последовательно несколько скриптов, который ты можешь запускать по отдельности:
  - `yarn typecheck`
  - `yarn format`
  - `yarn lint`

- все что касается наших инструментов, лежит тут: https://github.com/atls/tools/tree/master. 
  - Вот например наш tsconfig: https://github.com/atls/tools/blob/master/config/typescript/src/index.ts
  - А вот конфиг нашего вебпака: https://github.com/atls/tools/blob/master/code/code-service/src/webpack.config.ts

- Наш `yarn` обновляется следующей командой - `yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js` из корня проекта. Проверяется через `yarn -v`
