### ISSUE TITLE
пофиксить ошибки линтера

### ISSUE THREAD

**Issue by kirill-ivanovvv** [atls/reactjs#145]
### Описание бага

большое количество ошибок линтера

### Воспроизведение

при запуске `yarn check`

### Ожидаемое поведение

отсутствие ошибок линтера

### Материалы

*

### Данные окружения

не зависит от окружения

**Comment by OsirisAnubiz** [comment]
Не начинать пока не доделаю [issue](https://github.com/atls/reactjs/issues/130). Там много где исправсил линт

**Comment by OsirisAnubiz** [comment]
@Nelfimov проблем с линтером больше нет, можно закрыть?

**Comment by Nelfimov** [comment]
да

**Comment by OsirisAnubiz** [comment]
решено в другом [issue](https://github.com/atls/reactjs/issues/130)
